# Generated by Django 5.2.4 on 2025-07-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobsite", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="jobrecord",
            constraint=models.UniqueConstraint(
                fields=("job_title", "work_year", "employee_residence"),
                name="unique_job_per_year_and_location",
            ),
        ),
    ]
