# Generated by Django 5.2.4 on 2025-07-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobsite", "0002_jobrecord_unique_job_per_year_and_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
